Mount the raw disk's system partition as the root

diff --git a/.github/workflows/image.yml b/.github/workflows/image.yml
--- a/.github/workflows/image.yml
+++ b/.github/workflows/image.yml
@@ -10,20 +10,27 @@ jobs:
 
     steps:
       - name: Create a raw disk image
+        shell: bash
         run: |
           dd if=/dev/zero of=simple-alpine.img bs=8M count=16
           (echo "start=2048, size=100MiB, type=c, bootable"; echo "type=83") | sfdisk simple-alpine.img
-          fdisk -l simple-alpine.img
 
-          mkfs.vfat -v -h 2048 simple-alpine.img $((100*1024*1024/1024))
-          mkfs.ext4 -E offset=$((512*(2048+100*1024*1024/512))) simple-alpine.img
+          # https://github.com/damianperera/mount-image-action/blob/v1/action.yml#L36
+          kpartx="$(sudo kpartx -avs simple-alpine.img)" || echo 1>&2 "ERROR: could not create loop devices for image"
+          echo $kpartx
+          blockDevices=($(grep -o 'loop.p.' <<<"$kpartx"))
+          sleep 0.5
+          boot=/dev/mapper/${blockDevices[0]}
+          root=/dev/mapper/${blockDevices[1]}
 
-      - name: Checkout
-        uses: actions/checkout@v2
+          echo "Boot: ${boot}"
+          echo "Root: ${root}"
 
-      - name: Make target folder
-        run: |
+          sudo mkfs.vfat -v ${boot}
+          sudo mkfs.ext4 ${root}
+
           mkdir target
+          sudo mount -t ext4 ${root} target
 
       - name: Have aarch64 environment
         uses: uraimo/run-on-arch-action@v2
@@ -33,6 +40,7 @@ jobs:
           run: |
             uname -a
             cat /etc/os-release
+
             apk add apk-tools-static
             apk.static \
               --arch $(uname -m) \
@@ -42,11 +50,10 @@ jobs:
               --root target/ \
               --initdb add alpine-base
 
-            ls -l */*
-
-      - name: Check the target
+      - name: Unmount image
         run: |
           ls -l target/
+          sudo umount target
 
       - name: Upload the disk image
         uses: actions/upload-artifact@v2
